# Generated by Django 3.2.3 on 2021-05-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('content', models.TextField(max_length=100, verbose_name='content')),
                ('category', models.IntegerField(verbose_name='category')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='create_date')),
                ('update_at', models.DateField(auto_now=True, verbose_name='update_date')),
            ],
        ),
    ]
